version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: taskboard
      POSTGRES_PASSWORD: taskboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tasknet

  api:
    build: ../backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskboard
      SPRING_DATASOURCE_USERNAME: taskboard
      SPRING_DATASOURCE_PASSWORD: taskboard
    ports:
      - "8080:8080"
    networks:
      - tasknet

  web:
    build: ../frontend
    depends_on:
      - api
    ports:
      - "4200:80"
    networks:
      - tasknet

networks:
  tasknet:

volumes:
  db_data:
